services:
  computer:
    build: .
    ports:
      - '8020:8020'
    working_dir: /home/root/code/
    user: root
    volumes:
      - ./:/home/root/code/
    command: "php -S 0.0.0.0:8020 -t /home/root/code/public"
    networks:
      - book_wise

  database:
    container_name: database
    image: postgres:15
    ports:
      - '5454:5432'
    environment:
      POSTGRES_DB: book_wise
      POSTGRES_USER: mathz
      POSTGRES_PASSWORD: leagueofdraven
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    networks:
      - book_wise

networks:
  book_wise: